Always return both regular and sort form of author name and book title
This way sorting can be done independently from the format chosen for display

Apart from affected files, also changed bookTest.php so it knows which is the sortform and to test for errors.
PHPunit test did not reveal errors but complained about missing methods, so probably a version mismatch with PHPUnit used to make the original test
```
ReflectionException: Method suite does not exist in phar://E:/XAMPP/pear/PHPUnit38.phar/phpunit/Runner/BaseTestRunner.php on line 113

Call Stack:
    1.0311     375848   1. {main}() E:\XAMPP\pear\PHPUnit38.phar:0
    1.0331     566872   2. PHPUnit_TextUI_Command::main() E:\XAMPP\pear\PHPUnit38.phar:614
    1.0331     570280   3. PHPUnit_TextUI_Command->run() phar://E:/XAMPP/pear/PHPUnit38.phar/phpunit/TextUI/Command.php:129
    1.0371     749464   4. PHPUnit_Runner_BaseTestRunner->getTest() phar://E:/XAMPP/pear/PHPUnit38.phar/phpunit/TextUI/Command.php:150
    1.0631    2471312   5. ReflectionClass->getMethod() phar://E:/XAMPP/pear/PHPUnit38.phar/phpunit/Runner/BaseTestRunner.php:113
```

TODO: make it so series indices are sorted numerically instead of alphanumeric.